theme: jekyll-theme-minimal
title: Hatim Tai | Experienced Software Developer | Freelancer | Formerly at Amazon
description: Hatim Tai's Portfolio and Blogging Site, Tune in for interesting blogs on Software Development and Programming.
